### ISSUE TITLE
Set gbb_flags has moved

### ISSUE THREAD

**Issue by spencer1248** [flatiron-labs/ubuntu-chromebook-installer#1]
See Sean Clerkins comment here:

https://johnlewis.ie/how-to-make-seabios-the-default-on-your-acer-c720/

The script is now at /usr/share/vboot/bin/set_gbb_flags.sh

I have verified that this fixes the issue.

**Comment by TSiege** [comment]
@tsiege also this more specific instructions should be added https://gist.github.com/mojombo/7c873f457df6abee5717

**Comment by TSiege** [comment]
Fixed
